# Use postgres/example user/password credentials
version: '3.4'

services:

    postgres:
        image: postgres:12.1
        restart: always
        environment:
            POSTGRES_USER: planter
            POSTGRES_PASSWORD: planter
            POSTGRES_DB: planter
        ports:
            - 5432:5432
        volumes:
            - /opt/planter/data/db:/var/lib/postgresql
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8090:8080
        depends_on:
            - postgres

    growmon:
        image: planter:latest
        restart: always
        ports:
            - "9000:9000"
            - "2022:22"
        devices:
            - "/sys/devices/platform/soc/fe200000.gpio:/sys/devices/platform/soc/fe200000.gpio"
            - "/sys/class/gpio:/sys/class/gpio"
            - "/dev/gpiomem:/dev/gpiomem"
            - "/dev/video0:/dev/video0"
        environment:
            APP_STAGE: docker
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: planter
            POSTGRES_PASSWORD: planter
            POSTGRES_SCHEMA: planter
        tty: true
        depends_on:
            - postgres

volumes:
    postgres_data: