[APP]
# Do we want to write the sensor output into the databse?
USE_DATABASE = 1
# Do we want to use webcam to capture timelapse images?
USE_WEBCAM = 1
# Do we want to use GPIO connected devices?.
USE_GPIO = 1
# time to wait between the next run.
SLEEP = 10.0
# A comma seperated string with all connected GPIO pins we want to use.
GPIO_LIST = "GPIO_PIN_1,GPIO_PIN_2"

# webcam settings
# Interval between the previous captured image in seconds.
WEBCAM_INTERVAL = 10.0
# Do we want to save captured images as png? If not jpeg will be used.
WEBCAM_USE_PNG = 1

# Database settings
POSTGRES_HOST = "192.168.2.150"
POSTGRES_PORT = 5432
POSTGRES_USERNAME = "planter"
POSTGRES_PASSWORD = "planter"
POSTGRES_SCHEMA = "planter"
POSTGRES_DATABASE = "planter"

# Format = 'Pin ID,Description'
[APP.GPIO]
GPIO_PIN_1 = 'D17,Room1'
#GPIO_PIN_2 = 'D27,Room2'

