[APP]
# If we want the backend stack on docker aka postgres
USE_DOCKER = 1
# Do we want to write the sensor output into the databse?
USE_DATABASE = 1
# Do we want to use webcam to capture timelapse images?
USE_WEBCAM = 0
# Do we want to use GPIO connected devices?.
USE_GPIO = 1
# Do we want to write all messages to an MQTT server?
USE_MQTT = 1
# time to wait between the next run.
SLEEP = 10.0
# A comma seperated string with all connected GPIO pins we want to use.
GPIO_LIST = "GPIO_PIN_1,GPIO_PIN_2"

# webcam settings
# camera devices
WEBCAM_DEVICE = "/dev/video0"
# Do we want to save captured images as png? If not jpeg will be used.
WEBCAM_USE_PNG = 1
# In which resolution should the image be saved?
WEBCAM_RESOLUTION = "1280x720"
WEBCAM_EXTRA_ARGS = "--no-banner -b -q -S 3 -D 1 -F 1 -i 0"
# Should we capture perdiodically images?
WEBCAM_TIMELAPSE = 1
# Interval between the previous captured image in seconds. 1800=30mins 3600=60mins 43200=12h 86400=24h
WEBCAM_INTERVAL = 1800.0

# MQTT settings
MQTT_SERVER_HOST = "mosquitto.lan.sublabs.com"
MQTT_SERVER_PORT = 1883
MQTT_SERVER_TOPIC = "planter"
MQTT_SERVER_USERNAME = "USERNAME"
MQTT_SERVER_PASSWORD = "PASSWORD"

# Database settings
POSTGRES_HOST = "192.168.2.150"
POSTGRES_PORT = 5432
POSTGRES_USERNAME = "planter"
POSTGRES_PASSWORD = "planter"
POSTGRES_SCHEMA = "planter"
POSTGRES_DATABASE = "planter"

# Format = 'Pin ID,Description'
[APP.GPIO]
GPIO_PIN_1 = 'D17,Room1'
GPIO_PIN_2 = 'D27,Room2'

